AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "GlueJobPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:*"
                  - "logs:*"
                Resource: "*"

  GlueJob:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "MyGlueJob"
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: "s3://demo-glue-bucket-rvl8vl/scripts/glue-script.py"
        PythonVersion: "3"
      DefaultArguments: 
        "--JOB_NAME": "glue-colbun"
        "--S3_INPUT_PATH": "s3://elecciones-venezuela/RESULTADOS_2024_CSV_V1.csv"
        "--S3_TEMP_DIR": "s3://aws-glue-assets-393573696710-us-east-2/temp_dir"
        "--S3_OUTPUT_PATH": "s3://aws-glue-assets-393573696710-us-east-2/output"        
      GlueVersion: "3.0"
      MaxCapacity: 2