# glue-job-template.yaml
Resources:
  MyGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: my-glue-job
      Role: arn:aws:iam::123456789012:role/AWSGlueServiceRole
      Command:
        Name: glueetl
        ScriptLocation: s3://demo-0b4e7a0e5fe/scripts/demo_pyspark.py
        PythonVersion: 3
      DefaultArguments:
        --TempDir: s3://my-bucket/temp/
        --S3_INPUT_PATH: s3://demo-0b4e7a0e5fe/input/x3000_oxford.csv
        --S3_OUTPUT_PATH: s3://demo-0b4e7a0e5fe/output/transformed_data
        --job-bookmark-option: job-bookmark-enable
        --extra-py-files: s3://my-bucket/scripts/dependencies.zip
      MaxRetries: 3
      NumberOfWorkers: 2
      WorkerType: Standard
