name: Deploy AWS Glue Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file glue-job.yaml \
            --stack-name GlueJobStack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Start Glue Job
        run: |
          aws glue start-job-run \
            --job-name MyGlueJob