name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload PySpark script to S3
        run: |
          aws s3 cp demo_pyspark.py s3://demo-0b4e7a0e5fe/scripts/demo_pyspark.py

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file glue-job-template.yaml \
            --stack-name my-glue-job-stack \
            --capabilities CAPABILITY_NAMED_IAM
